'use client';

/**
 * Kigumi Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles with cascade layers and applies theme classes.
 *
 * Current theme: default
 * Current palette: default
 * Current brand: blue
 *
 * To change themes, use: kigumi theme <name>
 * To change brand color, use: kigumi brand <color>
 */

// Prevent duplicate custom-element registrations when Web Awesome components
// share internal dependencies (e.g. toast-item internally uses progress-ring)
if (typeof customElements !== 'undefined') {
  const _ceDefine = customElements.define.bind(customElements);
  customElements.define = function (name: string, ctor: CustomElementConstructor, options?: ElementDefinitionOptions) {
    if (!customElements.get(name)) _ceDefine(name, ctor, options);
  };
}

// Import Web Awesome CSS with cascade layers for predictable specificity control
import '@/styles/layers.css';

// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\bwa-theme-\S+/g, '')
    .replace(/\bwa-palette-\S+/g, '')
    .replace(/\bwa-brand-\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-default');
  html.classList.add('wa-palette-default');
  html.classList.add('wa-brand-blue');
}

export {};
